namespace Microsoft.EntityFrameworkCore.Query;

public class AdHocNavigationsQueryGaussDBTest(NonSharedFixture fixture) : AdHocNavigationsQueryRelationalTestBase(fixture)
{
    private const string LateralSubquerySkip =
        "Local-only: current GaussDB version doesn't support LATERAL subqueries/APPLY patterns generated by the provider.";

    // Cannot write DateTime with Kind=Local to GaussDB type 'timestamp with time zone', only UTC is supported.
    public override Task Reference_include_on_derived_type_with_sibling_works()
        => Assert.ThrowsAsync<DbUpdateException>(() => base.Reference_include_on_derived_type_with_sibling_works());

    [ConditionalFact(Skip = LateralSubquerySkip)]
    public override Task Projection_with_multiple_includes_and_subquery_with_set_operation()
        => Task.CompletedTask;

    [ConditionalFact(Skip = LateralSubquerySkip)]
    public override Task Let_multiple_references_with_reference_to_outer()
        => Task.CompletedTask;

    [ConditionalFact(Skip = LateralSubquerySkip)]
    public override Task SelectMany_and_collection_in_projection_in_FirstOrDefault()
        => Task.CompletedTask;

    protected override ITestStoreFactory TestStoreFactory
        => GaussDBTestStoreFactory.Instance;
}
