using Microsoft.EntityFrameworkCore.TestModels.Northwind;
using Xunit.Sdk;

namespace Microsoft.EntityFrameworkCore.Query;

#nullable disable

public class NorthwindMiscellaneousQueryGaussDBTest : NorthwindMiscellaneousQueryRelationalTestBase<
    NorthwindQueryGaussDBFixture<NoopModelCustomizer>>
{
    private const string LateralSubquerySkip =
        "Local-only: current GaussDB version doesn't support LATERAL subqueries/APPLY patterns generated by the provider.";
    private const string ArrayLikeSemanticsSkip =
        "Local-only: current GaussDB array LIKE/ILIKE ALL/ANY semantics don't match the PostgreSQL behavior expected by these tests.";
    private const string ContainsDateTypeMappingSkip =
        "Local-only: current GaussDB translation for Contains(DateTime.Date) still mixes timestamptz and timestamp without time zone mappings.";

    // ReSharper disable once UnusedParameter.Local
    public NorthwindMiscellaneousQueryGaussDBTest(
        NorthwindQueryGaussDBFixture<NoopModelCustomizer> fixture,
        ITestOutputHelper testOutputHelper)
        : base(fixture)
    {
        ClearLog();
        Fixture.TestSqlLoggerFactory.SetTestOutputHelper(testOutputHelper);
    }

    [ConditionalTheory(Skip = "Local-only: current provider behavior no longer throws for this shape, and reconciling the expectation would require deeper test-behavior analysis.")]
    [MemberData(nameof(IsAsyncData))]
    public override Task Entity_equality_contains_with_list_of_null(bool async)
    {
        _ = async;
        return Task.CompletedTask;
    }

    public override async Task Query_expression_with_to_string_and_contains(bool async)
    {
        await base.Query_expression_with_to_string_and_contains(async);

        AssertSql(
            """
SELECT o."CustomerID"
FROM "Orders" AS o
WHERE o."OrderDate" IS NOT NULL AND COALESCE(o."EmployeeID"::text, '') LIKE '%7%'
""");
    }

    public override async Task Select_expression_date_add_year(bool async)
    {
        await base.Select_expression_date_add_year(async);

        AssertSql(
            """
SELECT o."OrderDate" + INTERVAL '1 years' AS "OrderDate"
FROM "Orders" AS o
WHERE o."OrderDate" IS NOT NULL
""");
    }

    [Theory]
    [MemberData(nameof(IsAsyncData))]
    public async Task Select_expression_date_add_year_param(bool async)
    {
        var years = 2;

        await AssertQuery(
            async,
            ss => ss.Set<Order>().Where(o => o.OrderDate != null)
                .Select(
                    o => new Order { OrderDate = o.OrderDate.Value.AddYears(years) }),
            e => e.OrderDate);

        AssertSql(
            """
@years='2'

SELECT o."OrderDate" + CAST((@years::text || ' years') AS interval) AS "OrderDate"
FROM "Orders" AS o
WHERE o."OrderDate" IS NOT NULL
""");
    }

    [Theory]
    [MemberData(nameof(IsAsyncData))]
    public async Task DateTime_subtract_TimeSpan(bool async)
    {
        await AssertQuery(
            async,
            ss => ss.Set<Order>().Where(o => o.OrderDate - TimeSpan.FromDays(1) == new DateTime(1997, 10, 8)));

        AssertSql(
            """
SELECT o."OrderID", o."CustomerID", o."EmployeeID", o."OrderDate"
FROM "Orders" AS o
WHERE o."OrderDate" - INTERVAL '1 00:00:00' = TIMESTAMP '1997-10-08T00:00:00'
""");
    }

    [Theory]
    [MemberData(nameof(IsAsyncData))]
    public async Task DateTimeFunction_subtract_DateTime(bool async)
    {
        await AssertFirst(
            async,
            ss => ss.Set<Order>().Where(o => o.OrderDate != null)
                .Select(o => new { Elapsed = (DateTime.Today - ((DateTime)o.OrderDate).Date).Days }));

        AssertSql(
            """
SELECT floor(date_part('day', date_trunc('day', now()::timestamp) - date_trunc('day', o."OrderDate")))::int AS "Elapsed"
FROM "Orders" AS o
WHERE o."OrderDate" IS NOT NULL
LIMIT 1
""");
    }

    public override Task Add_minutes_on_constant_value(bool async)
        => AssertQuery(
            async,
            ss => ss.Set<Order>().Where(c => c.OrderID < 10500)
                .OrderBy(o => o.OrderID)
                .Select(o => new { Test = new DateTime(1900, 1, 1, 0, 0, 0, DateTimeKind.Utc).AddMinutes(o.OrderID % 25) }),
            assertOrder: true,
            elementAsserter: (e, a) => AssertEqual(e.Test, a.Test));

    public override async Task Client_code_using_instance_method_throws(bool async)
    {
        Assert.Equal(
            CoreStrings.ClientProjectionCapturingConstantInMethodInstance(
                "Microsoft.EntityFrameworkCore.Query.NorthwindMiscellaneousQueryGaussDBTest",
                "InstanceMethod"),
            (await Assert.ThrowsAsync<InvalidOperationException>(
                () => base.Client_code_using_instance_method_throws(async))).Message);

        AssertSql();
    }

    public override async Task Client_code_using_instance_in_static_method(bool async)
    {
        Assert.Equal(
            CoreStrings.ClientProjectionCapturingConstantInMethodArgument(
                "Microsoft.EntityFrameworkCore.Query.NorthwindMiscellaneousQueryGaussDBTest",
                "StaticMethod"),
            (await Assert.ThrowsAsync<InvalidOperationException>(
                () => base.Client_code_using_instance_in_static_method(async))).Message);

        AssertSql();
    }

    public override async Task Client_code_using_instance_in_anonymous_type(bool async)
    {
        Assert.Equal(
            CoreStrings.ClientProjectionCapturingConstantInTree(
                "Microsoft.EntityFrameworkCore.Query.NorthwindMiscellaneousQueryGaussDBTest"),
            (await Assert.ThrowsAsync<InvalidOperationException>(
                () => base.Client_code_using_instance_in_anonymous_type(async))).Message);

        AssertSql();
    }

    public override async Task Client_code_unknown_method(bool async)
    {
        await AssertTranslationFailedWithDetails(
            () => base.Client_code_unknown_method(async),
            CoreStrings.QueryUnableToTranslateMethod(
                "Microsoft.EntityFrameworkCore.Query.NorthwindMiscellaneousQueryTestBase<Microsoft.EntityFrameworkCore.Query.NorthwindQueryGaussDBFixture<Microsoft.EntityFrameworkCore.TestUtilities.NoopModelCustomizer>>",
                nameof(UnknownMethod)));

        AssertSql();
    }

    public override async Task Max_on_empty_sequence_throws(bool async)
    {
        await Assert.ThrowsAsync<InvalidOperationException>(() => base.Max_on_empty_sequence_throws(async));

        AssertSql(
            """
SELECT (
    SELECT max(o."OrderID")
    FROM "Orders" AS o
    WHERE c."CustomerID" = o."CustomerID") AS "Max"
FROM "Customers" AS c
""");
    }

    public override async Task Entity_equality_through_subquery_composite_key(bool async)
    {
        var message = (await Assert.ThrowsAsync<InvalidOperationException>(
            () => base.Entity_equality_through_subquery_composite_key(async))).Message;

        Assert.Equal(
            CoreStrings.EntityEqualityOnCompositeKeyEntitySubqueryNotSupported("==", nameof(OrderDetail)),
            message);

        AssertSql();
    }

    public override async Task
        Select_DTO_constructor_distinct_with_collection_projection_translated_to_server_with_binding_after_client_eval(bool async)
    {
        // Allow binding of expressions after projection has turned to client eval. Issue #24478.
        await Assert.ThrowsAsync<TrueException>(
            () => base
                .Select_DTO_constructor_distinct_with_collection_projection_translated_to_server_with_binding_after_client_eval(async));

        AssertSql(
            """
SELECT o0."CustomerID", o1."OrderID", o1."CustomerID", o1."EmployeeID", o1."OrderDate"
FROM (
    SELECT DISTINCT o."CustomerID"
    FROM "Orders" AS o
    WHERE o."OrderID" < 10300
) AS o0
LEFT JOIN "Orders" AS o1 ON o0."CustomerID" = o1."CustomerID"
ORDER BY o0."CustomerID" NULLS FIRST
""");
    }

    // TODO: #3406
    [ConditionalTheory(Skip = LateralSubquerySkip)]
    public override Task Where_nanosecond_and_microsecond_component(bool async)
        => AssertTranslationFailed(() => base.Where_nanosecond_and_microsecond_component(async));

    // TODO: Array tests can probably move to the dedicated ArrayQueryTest suite

    #region Array contains

    // Note that this also takes care of array.Any(x => x == y)
    [ConditionalTheory]
    [MemberData(nameof(IsAsyncData))]
    public async Task Array_Contains_constant(bool async)
    {
        await AssertQuery(
            async,
            ss => ss.Set<Customer>().Where(c => new[] { "ALFKI", "ANATR" }.Contains(c.CustomerID)));

        // Note: for constant lists there's no advantage in using the GaussDB-specific x = ANY (a b, c), unlike
        // for parameterized lists.

        AssertSql(
            """
SELECT c."CustomerID", c."Address", c."City", c."CompanyName", c."ContactName", c."ContactTitle", c."Country", c."Fax", c."Phone", c."PostalCode", c."Region"
FROM "Customers" AS c
WHERE c."CustomerID" IN ('ALFKI', 'ANATR')
""");
    }

    [ConditionalTheory]
    [MemberData(nameof(IsAsyncData))]
    public async Task Array_Contains_parameter(bool async)
    {
        var regions = new[] { "UK", "SP" };

        await AssertQuery(
            async,
            ss => ss.Set<Customer>().Where(c => regions.Contains(c.Region)));

        // Instead of c."Region" IN ('UK', 'SP') we generate the GaussDB-specific x = ANY (a, b, c), which can
        // be parameterized.
        // Ideally parameter sniffing would allow us to produce SQL without the null check since the regions array doesn't contain one
        // (see https://github.com/aspnet/EntityFrameworkCore/issues/17598).
        AssertSql(
            """
@regions1='UK'
@regions2='SP'

SELECT c."CustomerID", c."Address", c."City", c."CompanyName", c."ContactName", c."ContactTitle", c."Country", c."Fax", c."Phone", c."PostalCode", c."Region"
FROM "Customers" AS c
WHERE c."Region" IN (@regions1, @regions2)
""");
    }

    [ConditionalTheory]
    [MemberData(nameof(IsAsyncData))]
    public async Task Array_Contains_parameter_with_null(bool async)
    {
        var regions = new[] { "UK", "SP", null };

        await AssertQuery(
            async,
            ss => ss.Set<Customer>().Where(c => regions.Contains(c.Region)));

        // Instead of c."Region" IN ('UK', 'SP') we generate the GaussDB-specific x = ANY (a, b, c), which can
        // be parameterized.
        // Ideally parameter sniffing would allow us to produce SQL with an optimized null check (no need to check the array server-side)
        // (see https://github.com/aspnet/EntityFrameworkCore/issues/17598).
        AssertSql(
            """
@regions1='UK'
@regions2='SP'

SELECT c."CustomerID", c."Address", c."City", c."CompanyName", c."ContactName", c."ContactTitle", c."Country", c."Fax", c."Phone", c."PostalCode", c."Region"
FROM "Customers" AS c
WHERE c."Region" IN (@regions1, @regions2) OR c."Region" IS NULL
""");
    }

    #endregion Array contains

    #region Any/All Like

    [ConditionalTheory(Skip = ArrayLikeSemanticsSkip)]
    [MemberData(nameof(IsAsyncData))]
    public async Task Array_Any_Like(bool async)
    {
        await using var context = CreateContext();

        var collection = new[] { "A%", "B%", "C%" };
        var query = context.Set<Customer>().Where(c => collection.Any(y => EF.Functions.Like(c.Address, y)));
        var result = async ? await query.ToListAsync() : query.ToList();

        Assert.Equal(
        [
            "ANATR",
                "BERGS",
                "BOLID",
                "CACTU",
                "COMMI",
                "CONSH",
                "FISSA",
                "FRANK",
                "GODOS",
                "GOURL",
                "HILAA",
                "HUNGC",
                "LILAS",
                "LINOD",
                "PERIC",
                "QUEEN",
                "RANCH",
                "RICAR",
                "SUPRD",
                "TORTU",
                "TRADH",
                "WANDK"
        ], result.Select(e => e.CustomerID));

        AssertSql(
            """
@collection={ 'A%', 'B%', 'C%' } (DbType = Object)

SELECT c."CustomerID", c."Address", c."City", c."CompanyName", c."ContactName", c."ContactTitle", c."Country", c."Fax", c."Phone", c."PostalCode", c."Region"
FROM "Customers" AS c
WHERE c."Address" LIKE ANY (@collection)
""");
    }

    [ConditionalTheory(Skip = ArrayLikeSemanticsSkip)]
    [MemberData(nameof(IsAsyncData))]
    public async Task Array_All_Like(bool async)
    {
        await using var context = CreateContext();

        var collection = new[] { "A%", "B%", "C%" };
        var query = context.Set<Customer>().Where(c => collection.All(y => EF.Functions.Like(c.Address, y)));
        var result = async ? await query.ToListAsync() : query.ToList();

        Assert.Empty(result);

        AssertSql(
            """
@collection={ 'A%', 'B%', 'C%' } (DbType = Object)

SELECT c."CustomerID", c."Address", c."City", c."CompanyName", c."ContactName", c."ContactTitle", c."Country", c."Fax", c."Phone", c."PostalCode", c."Region"
FROM "Customers" AS c
WHERE c."Address" LIKE ALL (@collection)
""");
    }

    [ConditionalTheory(Skip = ArrayLikeSemanticsSkip)]
    [MemberData(nameof(IsAsyncData))]
    public async Task Array_All_Like_negated(bool async)
    {
        await using var context = CreateContext();

        var collection = new[] { "A%", "B%", "C%" };
        var query = context.Set<Customer>().Where(c => !collection.All(y => EF.Functions.Like(c.Address, y)));
        var result = async ? await query.ToListAsync() : query.ToList();

        Assert.NotEmpty(result);

        AssertSql(
            """
@collection={ 'A%', 'B%', 'C%' } (DbType = Object)

SELECT c."CustomerID", c."Address", c."City", c."CompanyName", c."ContactName", c."ContactTitle", c."Country", c."Fax", c."Phone", c."PostalCode", c."Region"
FROM "Customers" AS c
WHERE NOT (c."Address" LIKE ALL (@collection))
""");
    }

    [ConditionalTheory(Skip = ArrayLikeSemanticsSkip)]
    [MemberData(nameof(IsAsyncData))]
    public async Task Array_Any_ILike(bool async)
    {
        await using var context = CreateContext();

        var collection = new[] { "a%", "b%", "c%" };
        var query = context.Set<Customer>().Where(c => collection.Any(y => EF.Functions.ILike(c.Address, y)));
        var result = async ? await query.ToListAsync() : query.ToList();

        Assert.Equal(
        [
            "ANATR",
                "BERGS",
                "BOLID",
                "CACTU",
                "COMMI",
                "CONSH",
                "FISSA",
                "FRANK",
                "GODOS",
                "GOURL",
                "HILAA",
                "HUNGC",
                "LILAS",
                "LINOD",
                "PERIC",
                "QUEEN",
                "RANCH",
                "RICAR",
                "SUPRD",
                "TORTU",
                "TRADH",
                "WANDK"
        ], result.Select(e => e.CustomerID));

        AssertSql(
            """
@collection={ 'a%', 'b%', 'c%' } (DbType = Object)

SELECT c."CustomerID", c."Address", c."City", c."CompanyName", c."ContactName", c."ContactTitle", c."Country", c."Fax", c."Phone", c."PostalCode", c."Region"
FROM "Customers" AS c
WHERE c."Address" ILIKE ANY (@collection)
""");
    }

    [ConditionalTheory(Skip = ArrayLikeSemanticsSkip)]
    [MemberData(nameof(IsAsyncData))]
    public async Task Array_Any_ILike_negated(bool async)
    {
        await using var context = CreateContext();

        var collection = new[] { "a%", "b%", "c%" };
        var query = context.Set<Customer>().Where(c => !collection.Any(y => EF.Functions.ILike(c.Address, y)));
        var result = async ? await query.ToListAsync() : query.ToList();

        Assert.Equal(
        [
            "ALFKI",
            "ANTON",
            "AROUT",
            "BLAUS",
            "BLONP"
        ], result.Select(e => e.CustomerID).Order().Take(5));

        AssertSql(
            """
@collection={ 'a%', 'b%', 'c%' } (DbType = Object)

SELECT c."CustomerID", c."Address", c."City", c."CompanyName", c."ContactName", c."ContactTitle", c."Country", c."Fax", c."Phone", c."PostalCode", c."Region"
FROM "Customers" AS c
WHERE NOT (c."Address" ILIKE ANY (@collection))
""");
    }

    [ConditionalTheory(Skip = ArrayLikeSemanticsSkip)]
    [MemberData(nameof(IsAsyncData))]
    public async Task Array_All_ILike(bool async)
    {
        await using var context = CreateContext();

        var collection = new[] { "a%", "b%", "c%" };
        var query = context.Set<Customer>().Where(c => collection.All(y => EF.Functions.ILike(c.Address, y)));
        var result = async ? await query.ToListAsync() : query.ToList();

        Assert.Empty(result);

        AssertSql(
            """
@collection={ 'a%', 'b%', 'c%' } (DbType = Object)

SELECT c."CustomerID", c."Address", c."City", c."CompanyName", c."ContactName", c."ContactTitle", c."Country", c."Fax", c."Phone", c."PostalCode", c."Region"
FROM "Customers" AS c
WHERE c."Address" ILIKE ALL (@collection)
""");
    }

    #endregion Any/All Like

    [ConditionalFact(Skip = LateralSubquerySkip)] // #1560
    public Task Lateral_join_with_table_is_rewritten_with_subquery()
    {
        return Task.CompletedTask;
    }

    [ConditionalTheory(Skip = LateralSubquerySkip)]
    [MemberData(nameof(IsAsyncData))]
    public override Task Correlated_collection_with_distinct_without_default_identifiers_projecting_columns(bool async)
    {
        _ = async;
        return Task.CompletedTask;
    }

    [ConditionalTheory(Skip = LateralSubquerySkip)]
    [MemberData(nameof(IsAsyncData))]
    public override Task Correlated_collection_with_distinct_without_default_identifiers_projecting_columns_with_navigation(bool async)
    {
        _ = async;
        return Task.CompletedTask;
    }

    [ConditionalTheory(Skip = LateralSubquerySkip)]
    [MemberData(nameof(IsAsyncData))]
    public override Task SelectMany_correlated_with_Select_value_type_and_DefaultIfEmpty_in_selector(bool async)
    {
        _ = async;
        return Task.CompletedTask;
    }

    [ConditionalTheory(Skip = LateralSubquerySkip)]
    [MemberData(nameof(IsAsyncData))]
    public override Task DefaultIfEmpty_in_subquery_nested_filter_order_comparison(bool async)
    {
        _ = async;
        return Task.CompletedTask;
    }

    [ConditionalTheory(Skip = LateralSubquerySkip)]
    [MemberData(nameof(IsAsyncData))]
    public override Task Complex_nested_query_doesnt_try_binding_to_grandparent_when_parent_returns_complex_result(bool async)
    {
        _ = async;
        return Task.CompletedTask;
    }

    [ConditionalTheory(Skip = LateralSubquerySkip)]
    [MemberData(nameof(IsAsyncData))]
    public override Task Select_subquery_recursive_trivial(bool async)
    {
        _ = async;
        return Task.CompletedTask;
    }

    [ConditionalTheory(Skip = LateralSubquerySkip)]
    [MemberData(nameof(IsAsyncData))]
    public override Task Select_correlated_subquery_ordered(bool async)
    {
        _ = async;
        return Task.CompletedTask;
    }

    [ConditionalTheory(Skip = LateralSubquerySkip)]
    [MemberData(nameof(IsAsyncData))]
    public override Task SelectMany_correlated_subquery_hard(bool async)
    {
        _ = async;
        return Task.CompletedTask;
    }

    [ConditionalTheory(Skip = ContainsDateTypeMappingSkip)]
    [MemberData(nameof(IsAsyncData))]
    public override Task Contains_with_DateTime_Date(bool async)
    {
        _ = async;
        return Task.CompletedTask;
    }

    protected override void ClearLog()
        => Fixture.TestSqlLoggerFactory.Clear();

    private void AssertSql(params string[] expected)
        => Fixture.TestSqlLoggerFactory.AssertBaseline(expected);
}
